version: "3"

services:
  app:
    image: platziapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
    command: node --inspect index.js

  db:
    image: mongo
